### ISSUE TITLE
Data received via publish is not reactive

### ISSUE THREAD

**Issue by benmgreene** [GetStream/stream-meteor#4]
I've setup a subscription to a notification feed:

```
Meteor.subscribe('Stream.feeds.user_notifications', notifications_length.get(), User.current()._id)
```

And I can get activity from this feed:

```
Stream.feeds.user_notifications.find({}, {sort: {created_at: -1}}).fetch()
```

However, if one of the notifications is marked as read, the fetched activity does **not** get updated (as it would if it were a typical document returned by a Meteor collection).

So, the question is:  Is the activity _supposed_ to be reactive (and this is a bug), or is it not currently implemented to be reactive.  In the second case, is this a planned enhancement?

Thanks.

**Comment by matthisk** [comment]
At the moment we only handle `deleted` and `new` on realtime updates. I will add handling `changed` realtime to the backlog

**Comment by matthisk** [comment]
Wait I just remembered that it isn't that easy, the realtime subscriptions do not return a `changed` field when mark_seen or mark_read is changed, only the total number. What is you usecase for reactively updating this per activity? You could also store this data in your local database.

**Comment by benmgreene** [comment]
The use case is pretty simple -- a notification is read, so I'd like to a) mark it as read, and b) have the UI reactively adjust. Normally I'd do this via the reactivity of the data context, but I can easily handle it manually instead.

**Comment by benmgreene** [comment]
The reason why it'd so valuable to have the data context itself be reactive is if the the notification is rendered in more than one place.  You'd want a single change to the activity to reactively update all templates rendered with that activity in the data context.  I can work around this, but this type of reactivity will be pretty much expected by Meteor developers.

**Comment by matthisk** [comment]
This is currently not supported on the Getstream.io API because we do not propagate `changed` activities on realtime events, only the total count of `unread` and `unseen`. Somehow this should be stored locally in you own MongoDB, I do not directly see a good solution how this could be generically integrated in the integration library, if you have any please let me know. Otherwise you would have to manage this state in your local database (which could be kind of cumbersome). Btw I am working on you other feature proposal and it is almost finished, this will allow you to read unread and unseen state for you notification feeds from a Reactive Mongo Collection.

**Comment by benmgreene** [comment]
One thing I can think of would be to use reactive Session variables to keep track of read/seen status of each notification and then transform each activity (via `notifications.find({},{transform:...})`) to have the `is_read` and `is_seen` attributes function as `ReactiveVar`s. That would make it consistent within a single client, but still not consistent among many.

And yeah, the alternative to that is something server-side. I'd have to take a closer look at how it does what it does now.

Re: the other feature, that's great, thank you -- I think it'll be a big help.

**Comment by matthisk** [comment]
I have added support for this in 0.4.0, you can now read the stats (i.e. unread and unseen count) for notification feeds via Stream.feedManager.getNotificationFeedStats(userId), this collection will be updated reactively if you are subscribed to the notification feed publication: `Meteor.subscribe('Stream.feeds.notifiction');` be aware that the notification feed group configured in your `settings.json` is always going to be published under `Stream.feeds.notification` (and not `Stream.feeds.{notification_feed_group_name}`).
