### ISSUE TITLE
Unreliable reactive updates

### ISSUE THREAD

**Issue by benmgreene** [GetStream/stream-meteor#5]
Given the following query

```
Stream.feeds.user_inbox.find({}, {sort: {created_at: -1}})
```

I'm noticing very different behaviors when adding a single activity to a feed that is followed by two different users's `user_inbox` feeds.

In the first user's case, the `find()` updates almost immediately. But in the 2nd case (in a different browser on the same machine), the `find()` does not re-run at all.  A quick check of the Data Browser confirms that the activity made it to both users' feeds.

**Comment by matthisk** [comment]
Can you try this with 0.4.0, and report back if the issue is still arising. And what type of feed is feed group `user_inbox` here?

**Comment by benmgreene** [comment]
Will do.  It's a notification feed.

**Comment by benmgreene** [comment]
This issue has been resolved. Thanks!
